// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaWorkflow.Infraestrutura.BancoDados;

#nullable disable

namespace SistemaWorkflow.Infraestrutura.Migrations
{
    [DbContext(typeof(ContextoWorkflow))]
    partial class ContextoWorkflowModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Anexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstanciaProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TarefaProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UsuarioUploadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstanciaProcessoId");

                    b.HasIndex("TarefaProcessoId");

                    b.HasIndex("UsuarioUploadId");

                    b.ToTable("Anexos", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EhFinal")
                        .HasColumnType("bit");

                    b.Property<bool>("EhInicial")
                        .HasColumnType("bit");

                    b.Property<Guid?>("FormularioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid?>("ResponsavelEquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResponsavelUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlaMinutos")
                        .HasColumnType("int");

                    b.Property<Guid>("VersaoProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormularioId");

                    b.HasIndex("ResponsavelEquipeId");

                    b.HasIndex("ResponsavelUsuarioId");

                    b.HasIndex("VersaoProcessoId");

                    b.ToTable("Atividades", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.CampoFormulario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FormularioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Rotulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormularioId");

                    b.ToTable("CamposFormulario", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstanciaProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstanciaProcessoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipes", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.EquipeUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AdministradorEquipe")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EquipeUsuarios", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Formulario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Formularios", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.HistoricoTarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAcao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TarefaProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioExecutorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TarefaProcessoId");

                    b.HasIndex("UsuarioExecutorId");

                    b.ToTable("HistoricoTarefas", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.InstanciaProcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoIdentificador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioCriadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VersaoProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIdentificador")
                        .IsUnique();

                    b.HasIndex("UsuarioCriadorId");

                    b.HasIndex("VersaoProcessoId");

                    b.ToTable("InstanciasProcesso", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ChaveEntidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValoresAntigos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNovos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.OpcaoCampo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CampoFormularioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("TextoExibicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CampoFormularioId");

                    b.ToTable("OpcoesCampo", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfis", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.PerfilPermissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("PerfilPermissoes", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("Permissoes", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Processo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Processos", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.TarefaProcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcaoExecutada")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("AtividadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLimite")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EquipeResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstanciaProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioConclusorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("EquipeResponsavelId");

                    b.HasIndex("InstanciaProcessoId");

                    b.HasIndex("UsuarioConclusorId");

                    b.HasIndex("UsuarioResponsavelId");

                    b.ToTable("TarefasProcesso", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.TransicaoAtividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtividadeDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtividadeOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Condicao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("VersaoProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeDestinoId");

                    b.HasIndex("AtividadeOrigemId");

                    b.HasIndex("VersaoProcessoId");

                    b.ToTable("TransicoesAtividade", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.UsuarioPerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioPerfis", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.ValorCampo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CampoFormularioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstanciaProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TarefaProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampoFormularioId");

                    b.HasIndex("InstanciaProcessoId");

                    b.HasIndex("TarefaProcessoId");

                    b.ToTable("ValoresCampo", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.VersaoProcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("JustificativaValidacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumeroVersao")
                        .HasColumnType("int");

                    b.Property<Guid>("ProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioValidadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.HasIndex("UsuarioValidadorId");

                    b.ToTable("VersoesProcesso", (string)null);
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Anexo", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.InstanciaProcesso", "InstanciaProcesso")
                        .WithMany("Anexos")
                        .HasForeignKey("InstanciaProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.TarefaProcesso", "TarefaProcesso")
                        .WithMany()
                        .HasForeignKey("TarefaProcessoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "UsuarioUpload")
                        .WithMany()
                        .HasForeignKey("UsuarioUploadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstanciaProcesso");

                    b.Navigation("TarefaProcesso");

                    b.Navigation("UsuarioUpload");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Atividade", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Formulario", "Formulario")
                        .WithMany("Atividades")
                        .HasForeignKey("FormularioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Equipe", "ResponsavelEquipe")
                        .WithMany()
                        .HasForeignKey("ResponsavelEquipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "ResponsavelUsuario")
                        .WithMany()
                        .HasForeignKey("ResponsavelUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.VersaoProcesso", "VersaoProcesso")
                        .WithMany("Atividades")
                        .HasForeignKey("VersaoProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formulario");

                    b.Navigation("ResponsavelEquipe");

                    b.Navigation("ResponsavelUsuario");

                    b.Navigation("VersaoProcesso");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.CampoFormulario", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Formulario", "Formulario")
                        .WithMany("Campos")
                        .HasForeignKey("FormularioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formulario");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Comentario", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.InstanciaProcesso", "InstanciaProcesso")
                        .WithMany("Comentarios")
                        .HasForeignKey("InstanciaProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstanciaProcesso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.EquipeUsuario", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Equipe", "Equipe")
                        .WithMany("EquipeUsuarios")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("EquipeUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.HistoricoTarefa", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.TarefaProcesso", "TarefaProcesso")
                        .WithMany("Historicos")
                        .HasForeignKey("TarefaProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "UsuarioExecutor")
                        .WithMany("HistoricoTarefas")
                        .HasForeignKey("UsuarioExecutorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TarefaProcesso");

                    b.Navigation("UsuarioExecutor");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.InstanciaProcesso", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.VersaoProcesso", "VersaoProcesso")
                        .WithMany("Instancias")
                        .HasForeignKey("VersaoProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");

                    b.Navigation("VersaoProcesso");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.LogAuditoria", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.OpcaoCampo", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.CampoFormulario", "CampoFormulario")
                        .WithMany("Opcoes")
                        .HasForeignKey("CampoFormularioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampoFormulario");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.PerfilPermissao", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Perfil", "Perfil")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Permissao", "Permissao")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Processo", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Equipe", "Equipe")
                        .WithMany("Processos")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.TarefaProcesso", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Atividade", "Atividade")
                        .WithMany("Tarefas")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Equipe", "EquipeResponsavel")
                        .WithMany()
                        .HasForeignKey("EquipeResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.InstanciaProcesso", "InstanciaProcesso")
                        .WithMany("Tarefas")
                        .HasForeignKey("InstanciaProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "UsuarioConclusor")
                        .WithMany()
                        .HasForeignKey("UsuarioConclusorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "UsuarioResponsavel")
                        .WithMany()
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Atividade");

                    b.Navigation("EquipeResponsavel");

                    b.Navigation("InstanciaProcesso");

                    b.Navigation("UsuarioConclusor");

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.TransicaoAtividade", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Atividade", "AtividadeDestino")
                        .WithMany("TransicoesDestino")
                        .HasForeignKey("AtividadeDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Atividade", "AtividadeOrigem")
                        .WithMany("TransicoesOrigem")
                        .HasForeignKey("AtividadeOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.VersaoProcesso", "VersaoProcesso")
                        .WithMany()
                        .HasForeignKey("VersaoProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtividadeDestino");

                    b.Navigation("AtividadeOrigem");

                    b.Navigation("VersaoProcesso");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.UsuarioPerfil", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Perfil", "Perfil")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.ValorCampo", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.CampoFormulario", "CampoFormulario")
                        .WithMany("Valores")
                        .HasForeignKey("CampoFormularioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.InstanciaProcesso", "InstanciaProcesso")
                        .WithMany("ValoresCampos")
                        .HasForeignKey("InstanciaProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.TarefaProcesso", "TarefaProcesso")
                        .WithMany("ValoresCampos")
                        .HasForeignKey("TarefaProcessoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CampoFormulario");

                    b.Navigation("InstanciaProcesso");

                    b.Navigation("TarefaProcesso");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.VersaoProcesso", b =>
                {
                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Processo", "Processo")
                        .WithMany("Versoes")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaWorkflow.Dominio.Entidades.Usuario", "UsuarioValidador")
                        .WithMany()
                        .HasForeignKey("UsuarioValidadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Processo");

                    b.Navigation("UsuarioValidador");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Atividade", b =>
                {
                    b.Navigation("Tarefas");

                    b.Navigation("TransicoesDestino");

                    b.Navigation("TransicoesOrigem");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.CampoFormulario", b =>
                {
                    b.Navigation("Opcoes");

                    b.Navigation("Valores");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Equipe", b =>
                {
                    b.Navigation("EquipeUsuarios");

                    b.Navigation("Processos");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Formulario", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Campos");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.InstanciaProcesso", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Comentarios");

                    b.Navigation("Tarefas");

                    b.Navigation("ValoresCampos");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Perfil", b =>
                {
                    b.Navigation("PerfilPermissoes");

                    b.Navigation("UsuarioPerfis");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Permissao", b =>
                {
                    b.Navigation("PerfilPermissoes");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Processo", b =>
                {
                    b.Navigation("Versoes");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.TarefaProcesso", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("ValoresCampos");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("EquipeUsuarios");

                    b.Navigation("HistoricoTarefas");

                    b.Navigation("UsuarioPerfis");
                });

            modelBuilder.Entity("SistemaWorkflow.Dominio.Entidades.VersaoProcesso", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Instancias");
                });
#pragma warning restore 612, 618
        }
    }
}
